In [3]:
from collections import OrderedDict
import pandas as pd

data = OrderedDict([('data(xxx_a1)_first_type', 0.12),
                    ('data(xxx_a2)_first_type', 0.14),
                    ('test(xx_b15)_second_type', 0.15)])

In [4]:
data

OrderedDict([('data(xxx_a1)_first_type', 0.12),
             ('data(xxx_a2)_first_type', 0.14),
             ('test(xx_b15)_second_type', 0.15)])

In [5]:
data.keys()

odict_keys(['data(xxx_a1)_first_type', 'data(xxx_a2)_first_type', 'test(xx_b15)_second_type'])

In [6]:
data.values()

odict_values([0.12, 0.14, 0.15])

In [26]:
fields = ['Date', 'Name', 'SoldItem']

In [41]:
df = pd.read_csv(r'/Users/msaha/Work/Projects/Flock/fiveobjects/github/reference/data/sales.csv', sep='    ')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [42]:
df

Date                     Name          SoldItem
0   15-Jul                      Joe                TV
1   15-Jul                      Joe            Fridge
2   15-Jul                      Joe   Washing Machine
3   15-Jul                      Joe                TV
4   15-Jul                      Joe            Fridge
5   15-Jul                     Mary             Chair
6   15-Jul                     Mary            Fridge
7   16-Jul                      Joe            Fridge
8   16-Jul                      Joe            Fridge
9   16-Jul                      Tim   Washing Machine
10  17-Jul                      Joe   Washing Machine
11  17-Jul  Jimmy   Washing Machine              None
12  17-Jul                      Joe   Washing Machine
13  17-Jul                      Joe   Washing Machine

In [67]:
df_fridge = df[df['SoldItem'] == 'Fridge']

In [68]:
df_fridge

Date  Name SoldItem
6  15-Jul  Mary   Fridge

In [69]:
np.array(2,3,6)

NameError: name 'np' is not defined

In [70]:
import numpy as np

In [72]:
a = np.array([2,3,6])

In [73]:
a

array([2, 3, 6])

In [74]:
a.shape()

TypeError: 'tuple' object is not callable

In [75]:
shape(a)

NameError: name 'shape' is not defined

In [76]:
a

array([2, 3, 6])

In [89]:
a.reshape(1,3)

array([[2, 3, 6]])

In [97]:
b=np.arange(2, np.ceil(6 / 2) + 1).reshape(2, 2)

ValueError: cannot reshape array of size 2 into shape (2,2)

In [91]:
b

array([[2., 3.]])

In [92]:
a/b

ValueError: operands could not be broadcast together with shapes (3,) (1,2) 

In [98]:
df=pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [99]:
a = df[0:3]

0  1
0  1  2
1  3  4
2  5  6

In [102]:
b = df[3:]

In [103]:
b

0   1
3  7   8
4  9  10

In [184]:
a = [['t1', 10, 12], ['t2', 21, 45], ['t3', 12, 23]]

In [185]:
a = np.array(a)

In [186]:
a

array([['t1', '10', '12'],
       ['t2', '21', '45'],
       ['t3', '12', '23']], dtype='<U2')

In [187]:
a[0:,1]

array(['10', '21', '12'], dtype='<U2')

In [188]:
a[0:,2]

array(['12', '45', '23'], dtype='<U2')

In [189]:
b = a[0:,2].astype(int) - a[0:,1].astype(int)

In [190]:
b

array([ 2, 24, 11])

In [191]:
max=np.where(b==np.amax(b))

In [164]:
max[0][0]

1

In [192]:
min=np.where(b==np.amin(b))

In [166]:
min[0][0]

0

In [172]:
a[max[0][0]][0]

't2'

In [173]:
a

array([['t1', '10', '12'],
       ['t2', '21', '45'],
       ['t3', '12', '23']], dtype='<U2')

In [174]:
a.concatenate(b)

AttributeError: 'numpy.ndarray' object has no attribute 'concatenate'

In [175]:
a.insert(b)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

In [182]:
a[0:,3]=b

IndexError: index 3 is out of bounds for axis 1 with size 3

In [204]:
c = np.array([a[0:,0]], [b])

TypeError: data type not understood

In [197]:
c

array(['t1', 't2', 't3', '2', '24', '11'], dtype='<U21')

In [205]:
list_of_Strings = ['index', 'substance', 'container']
# a list with 3 lists, each list has a few values
index_list = [0,1,2]
substance_list = ['water','oil','acetone']
container_list = ['B100','B200','B300']
list_of_lists = [index_list, substance_list, container_list]

In [206]:
list_of_lists

[[0, 1, 2], ['water', 'oil', 'acetone'], ['B100', 'B200', 'B300']]

In [207]:
dict_dummy_2 = dict.fromkeys(list_of_Strings,0)
for i in range(len(list_of_Strings)):
    dict_dummy_2[list_of_Strings[i]] = list_of_lists[i]

In [208]:
dict_dummy_2

{'index': [0, 1, 2],
 'substance': ['water', 'oil', 'acetone'],
 'container': ['B100', 'B200', 'B300']}

In [209]:
dict(zip(list_of_Strings,list_of_lists))

{'index': [0, 1, 2],
 'substance': ['water', 'oil', 'acetone'],
 'container': ['B100', 'B200', 'B300']}

In [234]:
df = pd.DataFrame([['2019-07-05','2019-06-01'],['2019-07-18','2019-09-03']])

In [211]:
df[0]

0    2019-07-05
1    2019-07-18
Name: 0, dtype: object

In [227]:
df.loc[pd.to_datetime(df[0]) > pd.to_datetime(df[1]), "var"]=1
df.loc[pd.to_datetime(df[0]) <= pd.to_datetime(df[1]), "var"]=0

In [228]:
df

0           1  var
0  2019-07-05  2019-06-01  1.0
1  2019-07-18  2019-09-03  0.0

In [235]:
df['var']=np.where(pd.to_datetime(df[0])>pd.to_datetime(df[1]), 1, 0)

In [236]:
df

0           1  var
0  2019-07-05  2019-06-01    1
1  2019-07-18  2019-09-03    0