In [3]:
from collections import OrderedDict
import pandas as pd

data = OrderedDict([('data(xxx_a1)_first_type', 0.12),
                    ('data(xxx_a2)_first_type', 0.14),
                    ('test(xx_b15)_second_type', 0.15)])

In [4]:
data

OrderedDict([('data(xxx_a1)_first_type', 0.12),
             ('data(xxx_a2)_first_type', 0.14),
             ('test(xx_b15)_second_type', 0.15)])

In [5]:
data.keys()

odict_keys(['data(xxx_a1)_first_type', 'data(xxx_a2)_first_type', 'test(xx_b15)_second_type'])

In [6]:
data.values()

odict_values([0.12, 0.14, 0.15])

In [26]:
fields = ['Date', 'Name', 'SoldItem']

In [41]:
df = pd.read_csv(r'/Users/msaha/Work/Projects/Flock/fiveobjects/github/reference/data/sales.csv', sep='    ')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [42]:
df

Date                     Name          SoldItem
0   15-Jul                      Joe                TV
1   15-Jul                      Joe            Fridge
2   15-Jul                      Joe   Washing Machine
3   15-Jul                      Joe                TV
4   15-Jul                      Joe            Fridge
5   15-Jul                     Mary             Chair
6   15-Jul                     Mary            Fridge
7   16-Jul                      Joe            Fridge
8   16-Jul                      Joe            Fridge
9   16-Jul                      Tim   Washing Machine
10  17-Jul                      Joe   Washing Machine
11  17-Jul  Jimmy   Washing Machine              None
12  17-Jul                      Joe   Washing Machine
13  17-Jul                      Joe   Washing Machine

In [67]:
df_fridge = df[df['SoldItem'] == 'Fridge']

In [68]:
df_fridge

Date  Name SoldItem
6  15-Jul  Mary   Fridge

In [69]:
np.array(2,3,6)

NameError: name 'np' is not defined

In [70]:
import numpy as np

In [72]:
a = np.array([2,3,6])

In [73]:
a

array([2, 3, 6])

In [74]:
a.shape()

TypeError: 'tuple' object is not callable

In [75]:
shape(a)

NameError: name 'shape' is not defined

In [76]:
a

array([2, 3, 6])

In [89]:
a.reshape(1,3)

array([[2, 3, 6]])

In [97]:
b=np.arange(2, np.ceil(6 / 2) + 1).reshape(2, 2)

ValueError: cannot reshape array of size 2 into shape (2,2)

In [91]:
b

array([[2., 3.]])

In [92]:
a/b

ValueError: operands could not be broadcast together with shapes (3,) (1,2) 