In [1]:
from collections import OrderedDict
import pandas as pd

data = OrderedDict([('data(xxx_a1)_first_type', 0.12),
                    ('data(xxx_a2)_first_type', 0.14),
                    ('test(xx_b15)_second_type', 0.15)])

In [2]:
data

OrderedDict([('data(xxx_a1)_first_type', 0.12),
             ('data(xxx_a2)_first_type', 0.14),
             ('test(xx_b15)_second_type', 0.15)])

In [3]:
data.keys()

odict_keys(['data(xxx_a1)_first_type', 'data(xxx_a2)_first_type', 'test(xx_b15)_second_type'])

In [4]:
data.values()

odict_values([0.12, 0.14, 0.15])

In [5]:
fields = ['Date', 'Name', 'SoldItem']

In [6]:
df = pd.read_csv(r'/Users/msaha/Work/Projects/Flock/fiveobjects/github/reference/data/sales.csv', sep='    ')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [7]:
df

Date                     Name          SoldItem
0   15-Jul                      Joe                TV
1   15-Jul                      Joe            Fridge
2   15-Jul                      Joe   Washing Machine
3   15-Jul                      Joe                TV
4   15-Jul                      Joe            Fridge
5   15-Jul                     Mary             Chair
6   15-Jul                     Mary            Fridge
7   16-Jul                      Joe            Fridge
8   16-Jul                      Joe            Fridge
9   16-Jul                      Tim   Washing Machine
10  17-Jul                      Joe   Washing Machine
11  17-Jul  Jimmy   Washing Machine              None
12  17-Jul                      Joe   Washing Machine
13  17-Jul                      Joe   Washing Machine

In [8]:
df_fridge = df[df['SoldItem'] == 'Fridge']

In [9]:
df_fridge

Date  Name SoldItem
6  15-Jul  Mary   Fridge

In [12]:
import numpy as np

In [13]:
a = np.array([2,3,6])

In [14]:
a

array([2, 3, 6])

In [16]:
a

array([2, 3, 6])

In [17]:
a.reshape(1,3)

array([[2, 3, 6]])

In [20]:
df=pd.DataFrame([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [21]:
a = df[0:3]

In [22]:
b = df[3:]

In [23]:
b

0   1
3  7   8
4  9  10

In [24]:
a = [['t1', 10, 12], ['t2', 21, 45], ['t3', 12, 23]]

In [25]:
a = np.array(a)

In [26]:
a

array([['t1', '10', '12'],
       ['t2', '21', '45'],
       ['t3', '12', '23']], dtype='<U2')

In [27]:
a[0:,1]

array(['10', '21', '12'], dtype='<U2')

In [28]:
a[0:,2]

array(['12', '45', '23'], dtype='<U2')

In [29]:
b = a[0:,2].astype(int) - a[0:,1].astype(int)

In [30]:
b

array([ 2, 24, 11])

In [31]:
max=np.where(b==np.amax(b))

In [32]:
max[0][0]

1

In [33]:
min=np.where(b==np.amin(b))

In [34]:
min[0][0]

0

In [35]:
a[max[0][0]][0]

't2'

In [36]:
a

array([['t1', '10', '12'],
       ['t2', '21', '45'],
       ['t3', '12', '23']], dtype='<U2')

In [39]:
list_of_Strings = ['index', 'substance', 'container']
# a list with 3 lists, each list has a few values
index_list = [0,1,2]
substance_list = ['water','oil','acetone']
container_list = ['B100','B200','B300']
list_of_lists = [index_list, substance_list, container_list]

In [40]:
list_of_lists

[[0, 1, 2], ['water', 'oil', 'acetone'], ['B100', 'B200', 'B300']]

In [41]:
dict_dummy_2 = dict.fromkeys(list_of_Strings,0)
for i in range(len(list_of_Strings)):
    dict_dummy_2[list_of_Strings[i]] = list_of_lists[i]

In [42]:
dict_dummy_2

{'index': [0, 1, 2],
 'substance': ['water', 'oil', 'acetone'],
 'container': ['B100', 'B200', 'B300']}

In [43]:
dict(zip(list_of_Strings,list_of_lists))

{'index': [0, 1, 2],
 'substance': ['water', 'oil', 'acetone'],
 'container': ['B100', 'B200', 'B300']}

In [44]:
df = pd.DataFrame([['2019-07-05','2019-08-01'],['2019-08-18','2019-09-03'],['2019-10-02','2019-05-03']])

In [45]:
df[0]

0    2019-07-05
1    2019-08-18
2    2019-10-02
Name: 0, dtype: object

In [46]:
df.loc[pd.to_datetime(df[0]) > pd.to_datetime(df[1]), "var"]=1
df.loc[pd.to_datetime(df[0]) <= pd.to_datetime(df[1]), "var"]=0

In [47]:
df

0           1  var
0  2019-07-05  2019-08-01  0.0
1  2019-08-18  2019-09-03  0.0
2  2019-10-02  2019-05-03  1.0

In [48]:
df['var1']=np.where(pd.to_datetime(df[0])>pd.to_datetime('2019-07-31'), 1, 0)
df['var2']=np.where(pd.to_datetime(df[1]) > pd.to_datetime(df[0]), 1, 0)

In [49]:
df

0           1  var  var1  var2
0  2019-07-05  2019-08-01  0.0     0     1
1  2019-08-18  2019-09-03  0.0     1     1
2  2019-10-02  2019-05-03  1.0     1     0